name: 'Generate GitHub App Token'
description: 'Generates a GitHub App installation token for secure API calls'

inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'GitHub App private key'
    required: true

outputs:
  token:
    description: 'The generated GitHub App token'
    value: ${{ steps.generate.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Generate Token
      id: generate
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}
