name: Changeset Release

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    name: Create or Update Release PR
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changeset additions
        id: check_changesets
        run: |
          # Check if the commit adds new changesets (not just deletes them)
          git fetch origin main
          ADDED_CHANGESETS=$(git diff --name-status HEAD^..HEAD | grep "^A.*\.changeset/.*\.md$" | wc -l)
          echo "Added changesets: $ADDED_CHANGESETS"

          if [ "$ADDED_CHANGESETS" -gt 0 ]; then
            echo "new_changesets=true" >> $GITHUB_OUTPUT
          else
            echo "new_changesets=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check_changesets.outputs.new_changesets == 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        if: steps.check_changesets.outputs.new_changesets == 'true'
        run: npm ci

      - name: Generate GitHub App Token
        if: steps.check_changesets.outputs.new_changesets == 'true'
        id: generate-token
        uses: ./.github/actions/generate-token
        with:
          app_id: ${{ secrets.CHANGESET_APP_ID }}
          private_key: ${{ secrets.CHANGESET_APP_KEY }}

      - name: Create Release Pull Request
        if: steps.check_changesets.outputs.new_changesets == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset version
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
