name: Update Vercel Badge

on: deployment_status

jobs:
  update-badge:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get branch from SHA
        id: get-branch
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Get commit data
              const { data: commit } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.deployment.sha
              });
              
              // Get all refs
              const { data: refs } = await github.rest.git.listMatchingRefs({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/'
              });
              
              // Find the branch that contains this commit
              const branch = refs.find(ref => ref.object.sha === commit.sha);
              if (!branch) {
                throw new Error('No branch found for this commit');
              }
              
              const branchName = branch.ref.replace('refs/heads/', '');
              console.log('Found branch:', branchName);
              core.setOutput('branch', branchName);
            } catch (error) {
              console.error('Error finding branch:', error);
              core.setFailed(error.message);
            }

      - uses: actions/checkout@v4
        if: steps.get-branch.outputs.branch
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - name: Check if URL changed
        if: steps.get-branch.outputs.branch
        id: check-url
        uses: actions/github-script@v7
        env:
          NEW_URL: ${{ github.event.deployment_status.target_url }}
        with:
          script: |
            const fs = require('fs');

            // Read the README
            const content = fs.readFileSync('README.md', 'utf8');

            // Extract current URL from badge
            const urlMatch = content.match(/\[!\[Vercel Preview\].*?\]\((.*?)\)/);
            const currentUrl = urlMatch ? urlMatch[1] : '';
            const newUrl = process.env.NEW_URL;

            console.log('Current URL:', currentUrl);
            console.log('New URL:', newUrl);

            // Only proceed if URLs are different
            core.setOutput('url_changed', currentUrl !== newUrl);

      - name: Update Badge
        if: steps.get-branch.outputs.branch && steps.check-url.outputs.url_changed == 'true'
        uses: actions/github-script@v7
        env:
          NEW_URL: ${{ github.event.deployment_status.target_url }}
          BRANCH: ${{ steps.get-branch.outputs.branch }}
        with:
          script: |
            const fs = require('fs');

            try {
              const content = fs.readFileSync('README.md', 'utf8');
              const newBadge = `[![Vercel Preview](https://img.shields.io/github/deployments/gearsandcode/cartales-ai/Preview?label=vercel%20preview&logo=vercel&logoColor=white)](${process.env.NEW_URL})`;
              
              // Replace the existing badge
              const newContent = content.replace(/\[!\[Vercel Preview\].*?\]\(.*?\)/, newBadge);
              
              // Get the file's current state
              const { data: file } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                ref: process.env.BRANCH
              });
              
              // Update file with new content
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                message: 'Update preview URL [skip ci]',
                content: Buffer.from(newContent).toString('base64'),
                sha: file.sha,
                branch: process.env.BRANCH,
                committer: {
                  name: 'github-actions[bot]',
                  email: '41898282+github-actions[bot]@users.noreply.github.com'
                }
              });
              
              console.log('Badge updated successfully');
            } catch (error) {
              console.error('Error details:', error);
              core.setFailed(`Error updating badge: ${error.message}`);
            }
