name: Update Vercel Badge

on: deployment_status

jobs:
  update-badge:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.ref }}

      - name: Check if URL changed
        id: check-url
        uses: actions/github-script@v7
        env:
          NEW_URL: ${{ github.event.deployment_status.target_url }}
        with:
          script: |
            const fs = require('fs');

            // Read the README
            const content = fs.readFileSync('README.md', 'utf8');

            // Extract current URL from badge
            const urlMatch = content.match(/\[!\[Vercel Preview\].*?\]\((.*?)\)/);
            const currentUrl = urlMatch ? urlMatch[1] : '';
            const newUrl = process.env.NEW_URL;

            console.log('Current URL:', currentUrl);
            console.log('New URL:', newUrl);

            // Only proceed if URLs are different
            core.setOutput('url_changed', currentUrl !== newUrl);
            core.setOutput('current_url', currentUrl);

      - name: Update Badge
        if: steps.check-url.outputs.url_changed == 'true'
        uses: actions/github-script@v7
        env:
          NEW_URL: ${{ github.event.deployment_status.target_url }}
        with:
          script: |
            const fs = require('fs');

            try {
              const content = fs.readFileSync('README.md', 'utf8');
              const newBadge = `[![Vercel Preview](https://img.shields.io/github/deployments/gearsandcode/cartales-ai/Preview?label=vercel%20preview&logo=vercel&logoColor=white)](${process.env.NEW_URL})`;
              
              // Replace the existing badge
              const newContent = content.replace(/\[!\[Vercel Preview\].*?\]\(.*?\)/, newBadge);
              
              // Get the file's current state
              const { data: file } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                ref: context.payload.deployment.ref
              });
              
              // Update file with new content
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                message: 'Update preview URL [skip ci]',
                content: Buffer.from(newContent).toString('base64'),
                sha: file.sha,
                branch: context.payload.deployment.ref,
                committer: {
                  name: 'github-actions[bot]',
                  email: '41898282+github-actions[bot]@users.noreply.github.com'
                }
              });
              
              console.log('Badge updated successfully');
            } catch (error) {
              console.error('Error details:', error);
              core.setFailed(`Error updating badge: ${error.message}`);
            }
