name: Update Vercel Badge

on: deployment_status

jobs:
  update-badge:
    if: |
      github.event.deployment_status.state == 'success' && 
      !contains(github.event.deployment.ref, 'Update Vercel preview badge URL')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.ref }}
          fetch-depth: 0

      - name: Update README with Preview URL
        run: |
          echo "Current deployment URL: ${{ github.event.deployment_status.target_url }}"

          # First make sure we're on the right branch
          branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          if [ -z "$branch" ]; then
            branch="${{ github.event.deployment.ref }}"
          fi
          git checkout "$branch"

          # Replace the preview URL in README.md
          cat README.md | grep "Vercel Preview"
          sed -i 's|\[!\[Vercel Preview\].*\]([^)]*)|[![Vercel Preview](https://img.shields.io/github/deployments/gearsandcode/cartales-ai/Preview?label=vercel%20preview\&logo=vercel\&logoColor=white)](${{ github.event.deployment_status.target_url }})|' README.md

          echo "Git status after sed:"
          git status

          echo "Git diff:"
          git diff README.md

          if git diff --exit-code README.md; then
            echo "No changes to commit"
            exit 0
          fi

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update preview URL [skip actions]"
          git push origin "$branch"
