name: Update Vercel Badge

on: deployment_status

jobs:
  update-badge:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Update README with Preview URL
        run: |
          # Replace the preview URL in README.md
          sed -i -E "s|(Preview.*?logo=vercel&logoColor=white)\]\(.*?\)|\1](${{ github.event.deployment_status.target_url }})|" README.md

          # If there are changes, commit them
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update preview URL [skip actions]"
          git push origin HEAD:${{ github.head_ref || github.ref_name }}
