name: Update Vercel Badge

on: deployment_status

jobs:
  update-badge:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Early exit if badge update commit
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.deployment.sha
            });

            if (commit.commit.message.includes('Update preview URL')) {
              core.setFailed('Skipping badge update for badge commit');
              return;
            }

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.ref }}

      - name: Update Badge
        uses: actions/github-script@v7
        env:
          NEW_URL: ${{ github.event.deployment_status.target_url }}
        with:
          script: |
            const fs = require('fs');

            try {
              const content = fs.readFileSync('README.md', 'utf8');
              const newBadge = `[![Vercel Preview](https://img.shields.io/github/deployments/gearsandcode/cartales-ai/Preview?label=vercel%20preview&logo=vercel&logoColor=white)](${process.env.NEW_URL})`;
              
              // Check if URL has changed
              const urlMatch = content.match(/\[!\[Vercel Preview\].*?\]\((.*?)\)/);
              const currentUrl = urlMatch ? urlMatch[1] : '';
              
              if (currentUrl === process.env.NEW_URL) {
                console.log('URL unchanged, skipping update');
                return;
              }
              
              // Update badge
              const newContent = content.replace(/\[!\[Vercel Preview\].*?\]\(.*?\)/, newBadge);
              
              const { data: file } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                ref: context.ref
              });
              
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'README.md',
                message: 'Update preview URL [skip ci]',
                content: Buffer.from(newContent).toString('base64'),
                sha: file.sha,
                branch: context.ref,
                committer: {
                  name: 'github-actions[bot]',
                  email: '41898282+github-actions[bot]@users.noreply.github.com'
                }
              });
              
              console.log('Badge updated successfully');
            } catch (error) {
              core.setFailed(`Error updating badge: ${error.message}`);
            }
